# Generated by Django 5.2.1 on 2025-05-10 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_alter_recipe_cooking_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='catagories',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='cooking_time',
            new_name='cookingTime',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='instruction',
            new_name='instructions',
        ),
    ]
