# Generated by Django 5.2.1 on 2025-05-10 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_rename_catagories_recipe_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='imageUrl',
            field=models.ImageField(null=True, upload_to='recipe/images'),
        ),
    ]
