# Generated by Django 5.2.1 on 2025-05-27 08:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0005_alter_recipe_imageurl_alter_favorite_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('id', 'user')},
        ),
        migrations.AlterField(
            model_name='favorite',
            name='id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='recipe.recipe'),
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='recipe',
        ),
    ]
