# Generated by Django 5.2.1 on 2025-05-23 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(default='null', max_length=255),
            preserve_default=False,
        ),
    ]
