# Generated by Django 5.2.1 on 2025-05-27 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
