# Generated by Django 5.2.1 on 2025-05-28 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'ADMIN'), ('user', 'USER')], default='USER', max_length=255),
        ),
    ]
